### ISSUE TITLE
DoublePrefixInPath false positive for comments

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#134]
https://qa-reports.gentoo.org/output/gentoo-ci/output.html#sys-libs/ncurses

Apparently it gets confused by:

    # "ncurses" variant goes into "${EPREFIX}"/usr/include

It seems that I failed to account for comments properly. Could you suggest a sane-ish way of doing that?

**Comment by radhermit** [comment]
To do it properly you'd need a bash parser in order to know the context of the statement, whether it's in a comment or outside of one or how the argument is being used.

The best we can probably do for now is skip full commented lines (while ignoring inline comments) for this check since I think that usage shouldn't matter in those cases.

**Comment by radhermit** [comment]
I assume the false positives triggered by inline comments should be a lot less than full comment lines.
