### ISSUE TITLE
add check for perl gentoo version scheme

### ISSUE THREAD

**Issue by akhuettel** [pkgcore/pkgcheck#165]
This issue corresponds to https://bugs.gentoo.org/506378 for repoman. 

Basically the test should schematically work like this: 

if "ebuild inherits perl-module.eclass (direct or indirect)" and "ebuild defines DIST_VERSION" then
  VALUE1=${PV}
  VALUE2=$(gentoo-perlmod-version.pl --oneshot ${DIST_VERSION})
  test fails if VALUE1 != VALUE2
endif

where gentoo-perlmod-version.pl is provided by dev-perl/Gentoo-PerlMod-Version

* It would probably make sense to make this optional and non-default, since calling an external perl will slow pkgcheck down
* Rewriting it in python is not really feasible (ask kent\n for the ugly details...)

**Comment by radhermit** [comment]
The initial check implementation isn't explicitly enabled, but also shouldn't slow down pkgcheck much since it uses a client/server architecture instead of exec-ing a perl script per version check. To run the check, something like ``pkgcheck scan -c PerlCheck`` or any other way of explicitly enabling checks/keywords will currently work.

Also, it's been 10+ years since I've significantly done any perl so feel free to open some PRs if it's too ugly for you. :smile:

**Comment by radhermit** [comment]
Also, as a reference the current output for the check against the gentoo repo is the following:

```
dev-perl/Bio-DB-HTS-2.11: module version doesn't match package version: 2.11 -> 2.110.0
dev-perl/Bio-DB-HTS-3.01: module version doesn't match package version: 3.01 -> 3.10.0
dev-perl/Digest-CRC-0.220.0_p2: module version doesn't match package version: 0.22.2 -> 0.22.2
dev-perl/MooseX-ConfigFromFile-0.140.0: module version doesn't match package version: 0.13 -> 0.130.0
dev-perl/Term-Shell-0.90: module version doesn't match package version: 0.09 -> 0.90.0
dev-perl/Term-Shell-0.110: module version doesn't match package version: 0.11 -> 0.110.0
dev-perl/Text-VimColor-0.290.0: module version doesn't match package version: 0.28 -> 0.280.0
dev-perl/ZMQ-LibZMQ3-1.19.0: module version doesn't match package version: 1.19 -> 1.190.0
sci-biology/bioperl-db-1.6.9-r1: module version doesn't match package version: 1.006900 -> 1.6.900
```
