### ISSUE TITLE
Add filter by maintainer into 'pkgcheck scan'

### ISSUE THREAD

**Issue by trofi** [pkgcore/pkgcheck#171]
Today to scan packages related to me I run something like:
```
$ portageq --maintainer-email=slyfox@gentoo.org,toolchain@gentoo.org --repo=gentoo | awk '{ print "="$0 }' | xargs pkgcheck scan
```

Would be nice to target at all packages directly:
```
pkgcheck scan --maintainer-email=slyfox@gentoo.org,toolchain@gentoo.org
```

**Comment by radhermit** [comment]
I'd rather improve a separate query tool such as pquery that can be piped into pkgcheck rather than adding too many query-like features to pkgcheck. Basically I like to avoid maintaining the same type of functionality in multiple places and try keep individual tools focused on their separate tasks.

Currently, it seems like pquery is in order of magnitude slower than it should be for maintainer querying which should be fixed.

**Comment by radhermit** [comment]
Closing this since I think querying support should be left to a query-specify tool.
