### ISSUE TITLE
add CLI option to limit to newest non-vcs version

### ISSUE THREAD

**Issue by robbat2** [pkgcore/pkgcheck#184]
Issue #144 added some framework for limiting checks to newest non-vcs version (every slot), but there's no command-line option to enable the option.

Can an option please be added to make it usable in everyday runs of pkgcheck?

**Comment by mgorny** [comment]
What we mean here is that it would be nice to be able to alter some checks to run only on those versions via CLI, without changing the check in general.

**Comment by radhermit** [comment]
All it should take is a PR or two that change versioned result classes you want filtered from inheriting results.VersionResult to results.FilteredVersionResult instead.

**Comment by radhermit** [comment]
Then -v/--verbose will be the option that triggers showing or filtering the filtered results.

**Comment by radhermit** [comment]
Closing this as this support already exists as mentioned above using the -v/--verbose option (it's currently used for network-based checks). You just need to do some basic legwork of opening a PR changing result class inheritance as described above for results you think should support filtering.

I'm not going to implement this implicitly for all version results since it doesn't make sense for every single one of them, e.g. metadata error related results.

**Comment by radhermit** [comment]
Reopening because I can see the value in this after more thought.
