### ISSUE TITLE
Disable VariableInHomepage check

### ISSUE THREAD

**Issue by Whissi** [pkgcore/pkgcheck#185]
If you want to keep *VariableInHomepage* check added in #173 for reporting that's fine but unless I am mistaken PMS allows for variable usage in `HOMEPAGE` so *pkgcore* shouldn't warn and Gentoo CI shouldn't list that as issue.

**Comment by mgorny** [comment]
It's forbidden in devmanual, and via a long-standing policy (it was what I was taught when I joined Gentoo).

**Comment by Whissi** [comment]
Hrm, thanks, I found (https://github.com/gentoo/devmanual/commit/c97aec7f7e236bc917067763916530bfa05d6e31). Not sure if we should either update PMS in that case or drop this requirement which shouldn't make sense given that `HOMEPAGE` is part of metadata (I don't know if that was different 10+ years ago so that it made sense when this was added). I am concerned that PMS and tool enforcing standards will disagree...

@ulm *ping*

**Comment by mgorny** [comment]
You're forgetting that people are maintaining ebuilds, not machines. People don't enjoy doing variable substitution. People enjoy HOMEPAGE that they can easily visit without having to call third-party tools to process the ebuild which may be in some remote location. The gain from using variables is usually near zero, and usually is associated with attempting to reinvent compression, poorly.

**Comment by radhermit** [comment]
pkgcheck generally follows the devmanual where it is stricter than PMS since PMS doesn't always include limitations for various data field specificiations. For example, this makes it possible for the gentoo repo to have higher standards for ebuilds than overlays (which should generally be the case) and pkgcheck usually tries to respect that by making certain checks or results gentoo repo exclusive.

So in cases like this, if you get the devs responsible for the devmanual to agree with you (and make changes) then I'd be more open to looking to change/drop the check.

**Comment by Whissi** [comment]
Well, we had a discussion in IRC and we should just update documentation. I.e. it's suboptimal when something like that will suddenly show up and when you click you find an empty explanation so you start checking PMS... A reference to devmanual would help.

**Comment by radhermit** [comment]
Doc reference now added.

**Comment by radhermit** [comment]
Closing as the latest generated doc page that CI links to should have a devmanual ref now.
