### ISSUE TITLE
Invalid DeadUrl?

### ISSUE THREAD

**Issue by juippis** [pkgcore/pkgcheck#208]
Everytime I run `pkgcheck scan --net` against *net-im/telegram-desktop-bin* I get this error: 

>  DeadUrl: version 1.9.8: HOMEPAGE: 501 Server Error: Not Implemented for url: https://desktop.telegram.org/: https://desktop.telegram.org

However the homepage works just fine and doesn't seem to redirect. I'm not a webmaster, but it looks like they somehow block whatever pkgcheck is using thinking it's a bot? 

I get the same error with *net-im/telegram-desktop*. These are the only packages I've ran into this "problem" so far.

**Comment by radhermit** [comment]
The unfortunate side effect of network checks is that there are various situations that can cause invalid reports. Thus why one should generally double check the URL in a browser for certain types of failures.

In this case, it appears that upstream's nginx server has been configured to reject HEAD requests (GET requests appear to work fine). If that's the case they should at least be returning a 405 error instead (see https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/501).

To workaround this it would be possible to re-run requests that failed for certain types of error codes using GET instead (or just revert back to GET entirely since it should be possible to run the request without pulling the entire message body under streaming mode), but I'm not sure it's worth it right now.
