### ISSUE TITLE
false positive: masked package with version number

### ISSUE THREAD

**Issue by jonasstein** [pkgcore/pkgcheck#219]
Situation:
https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=197322029099bb21f0ad0f6aabb1558c837694ce

Yes, the version numbers were redundant and not elegant, but should not trigger a false alert.
![image](https://user-images.githubusercontent.com/298682/77984548-207eae00-7312-11ea-99cd-2d6cffccad29.png)

**Comment by radhermit** [comment]
Closing, since all the related package.mask entries used invalid package atoms missing '=' prefixes leading to ProfileError results being outputted and the bad masks being ignored. CI may need to raise it's priority for ProfileError results if they weren't apparent enough assuming that's how you currently consume pkgcheck results.

It's also possible to run `pkgcheck scan` in the profiles directory locally which would have shown the ProfileError results or `pkgcheck scan --commits` before committing which should have done the same.
