### ISSUE TITLE
Running for 2 explicitely named profiles will not output both if keywords missing

### ISSUE THREAD

**Issue by DerDakon** [pkgcore/pkgcheck#226]
I run pkgcheck with options ```--arches=hppa,sparc -p default/linux/sparc/17.0,default/linux/hppa/17.0 -k NonsolvableDepsInExp```.

It complained correctly:

```
x11-apps/xinit
  NonsolvableDepsInExp: version 1.4.1: nonsolvable depset(pdepend) keyword(hppa) exp profile (default/linux/hppa/17.0) (2 total): solutions: [ x11-terms/xterm ]
```

I stabilized xterm on hppa and now it comes up with:

```
x11-apps/xinit
  NonsolvableDepsInExp: version 1.4.1: nonsolvable depset(pdepend) keyword(sparc) exp profile (default/linux/sparc/17.0) (1 total): solutions: [ x11-terms/xterm ]
```

Also correct, but why did it not say this before?

**Comment by radhermit** [comment]
Note the phrase ``(2 total)`` in the first result, this means there are two scanned profiles that exhibit this failure. By default NonsolvableDep results are collapsed per unique depset otherwise failures will often cause the same error to be repeated many times -- once for each profile being scanned that has the same issue.

To show all the results run pkgcheck in verbose mode, i.e. add ``-v`` onto your option list for ``pkgcheck scan``.
