### ISSUE TITLE
pkgcheck scan: error: failed running git: fatal: ambiguous argument 'origin': unknown revision or path not in the working tree.

### ISSUE THREAD

**Issue by oxr463** [pkgcore/pkgcheck#232]
```sh
pkgcheck scan --commits
pkgcheck scan: error: failed running git: fatal: ambiguous argument 'origin': unknown revision or path not in the working tree.
```

**Comment by oxr463** [comment]
See: https://stackoverflow.com/a/61320225/8507637

**Comment by oxr463** [comment]
Source: https://github.com/pkgcore/pkgcheck/blob/master/src/pkgcheck/git.py

**Comment by radhermit** [comment]
Closing since the docs already mention this at https://github.com/pkgcore/pkgcheck/blob/master/src/pkgcheck/git.py#L340 which should automatically get added to the man page and website docs.

If you think more information or better wording could be added to make it more clear feel free to open a pull request.
