### ISSUE TITLE
^c unnecessarily discards git cache

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#244]
I sometimes want to cancel pkgcheck because I've run it with wrong args. However, when ^c in the middle of git cache update, it seems to discard the cache entirely and spend a lot of time rebuilding it on next run. It would be better if it just discarded the update and left old file alone.

**Comment by radhermit** [comment]
I haven't been able to reproduce this. The current logic only removes the cache file before generation if the cache version changed or the cache somehow got mutated behind pkgcheck's back.

The only thing I can see on a quick look that could cause this would be if you're hitting ctrl-c when the cache file is getting written via pickle.dump() since that's probably not atomic and to make it so pickle.dumps() would probably have to be used instead with manual atomic write handling.

**Comment by mgorny** [comment]
Hey, I'm good at breaking stuff that relies on exact timing! ;-)

Why not write it into temporary file, and use `rename()` to overwrite?

**Comment by mgorny** [comment]
or you could just use yer fancy atomic file class and dump to file object there

**Comment by radhermit** [comment]
It would be helpful if you could run pkgcheck with the --debug option enabled and paste the output or at least the relevant git repo cache lines here when you reproduce this. Doing so could help pinpoint why the cache gets rejected on load instead of me guessing what's going on.

**Comment by radhermit** [comment]
Otherwise if you've explicitly checked that the entire cache file gets blown away when this happens running with debug is probably less helpful.
