### ISSUE TITLE
Add a check for global use* function calls

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#25]
So far pkgcore complains about them loudly during cache regen. Would be nice if pkgcheck caught them too.

**Comment by radhermit** [comment]
It would interesting to combine this with doing more tests that force direct bash usage, i.e. we'd start up some ebd instances and start requesting various actions over them to perform tests.

**Comment by mgorny** [comment]
I wonder how much slowdown that would cause. It might be a better idea to store some important QA notices like this in cache somewhere.

**Comment by radhermit** [comment]
Closing as these should now be caught as MetadataErrors.

In this case pkgcore should force a new metadata regen (since the related file shouldn't exist due to being skipped from the error or exist but the checksum doesn't match in the case of local edits) causing a MetadataError to be thrown and redisplayed by pkgcheck such as the following:

MetadataError: version 11.32: attr(data): failed sourcing ebuild: external commands disallowed during metadata regen: 'use doc'
