### ISSUE TITLE
`--check GitCommitsCheck` should execute the check regardless of the repository

### ISSUE THREAD

**Issue by ezzieyguywuf** [pkgcore/pkgcheck#261]
When trying to enable this check on a repository other than `::gentoo`, `pkgcheck` errors-out with a (admittedly helpful) message that the current repo is not `::gentoo`.

Rather, I would expect the helpful message to warn me, but to still run through with the check. Since I have explicitly passed the flag, I think `pkgcheck` should attempt to run it and "user beware"

**Comment by radhermit** [comment]
All the other conditional check skips legitimately don't apply when the conditions they check for aren't met, e.g. overlay-specific checks. However, most of the checks flagged to only apply to the gentoo repo are due to the increased QA strictness for the main tree therefore I can see allowing them if explicitly selected.
