### ISSUE TITLE
consider supporting a repo-level result -> failure mapping when the --exit option is enabled

### ISSUE THREAD

**Issue by ezzieyguywuf** [pkgcore/pkgcheck#289]
I have an ebuild with an [invalid HOMEPAGE](https://github.com/ezzieyguywuf/gentoo-haskell/blob/longdescription/dev-haskell/converge/converge-0.1.0.1-r1.ebuild#L12).

pkgcheck [did not flag this](https://github.com/gentoo-haskell/gentoo-haskell/pull/1155/checks?check_run_id=1929310073) as an error.

[repoman did](https://github.com/gentoo-haskell/gentoo-haskell/pull/1155/checks?check_run_id=1929310243#step:6:13).

Is there a flag I'm missing in the pkgcheck call? Or is his a bug?

**Comment by radhermit** [comment]
Invalid in what way? At a glance I can't tell what's wrong with it.

If repoman had some related output, can you copy/paste the related lines instead of linking to a CI run? I can't find anything related in that run.

**Comment by ezzieyguywuf** [comment]
It got messed up due to a force push.

`HOMEPAGE="/dev/null"` was the invalid value.

repoman caught this as `HOMEPAGE.missingurischeme [fatal]1`

**Comment by radhermit** [comment]
pkgcheck should output a result similar to the following in that case:

``
BadHomepage: version 3.6: HOMEPAGE='/dev/null' lacks protocol
``

I'm not sure how or why it didn't but if you can reproduce that somehow (since I can't) it's a bug.

**Comment by ezzieyguywuf** [comment]
So, job 42 listed [here](https://github.com/gentoo-haskell/gentoo-haskell/actions) shows how repoman failed but pkgcheck passed.

I'll try to develop a minimal example that reproduces the issue.

**Comment by radhermit** [comment]
> So, job 42 listed [here](https://github.com/gentoo-haskell/gentoo-haskell/actions) shows how repoman failed but pkgcheck passed.

Oh, that's a different issue then. :smile:

pkgcheck has 4 levels for results -- error, warning, style, and info in order of severity, respectively. By default when using the `--exit` option for pkgcheck only error level results trigger exit code failures. If you read the man page, `--exit` allows options in order to fully customize what you'd like to trigger an exit failure.

In this case BadHomepage has a level of warning so it doesn't trigger a failure.

**Comment by ezzieyguywuf** [comment]
So really this is a philosophical question: repoman considers this a fatal error. pkgcheck calls it a warning.

What's the right answer?

**Comment by radhermit** [comment]
There's no right answer, that's why pkgcheck makes it configurable. In general I've tried to make error level results be for horrible/terribly bad situations but it's quite subjective in some cases. In this situation, bad HOMEPAGE values don't really affect the package manager much so it's a warning.

If you want to run CI for an overlay similar to how gentoo repo CI is run (https://qa-reports.gentoo.org/output/gentoo-ci/output.html) you'd either want to define a custom checkset for pkgcheck and use that as an argument for ``--exit`` or verbosely list non-error level exit keywords/checks (e.g. in this case ``--exit error,BadHomepage`` would have done what you wanted ('error' being an alias for all error level keywords).

I've suggested that Gentoo QA have an official pkgcheck.conf config that defines a standard set of options like this that map to what's used/expected for gentoo repo CI, but they haven't yet. In fact, pkgcheck isn't really mentioned anywhere in most official Gentoo docs so it's not really an official tool. :laughing:

**Comment by ezzieyguywuf** [comment]
> I've suggested that Gentoo QA have an official pkgcheck.conf config that defines a standard set of options like this that map to what's used/expected for gentoo repo CI

is this the kind of thing you had in mind? https://github.com/gentoo/gentoo/blob/master/metadata/qa-policy.conf

**Comment by radhermit** [comment]
> > I've suggested that Gentoo QA have an official pkgcheck.conf config that defines a standard set of options like this that map to what's used/expected for gentoo repo CI
> 
> is this the kind of thing you had in mind? https://github.com/gentoo/gentoo/blob/master/metadata/qa-policy.conf

Oh right I forgot about that, but I meant an actual pkgcheck.conf config since pkgcheck supports reading repo-specific configs from `metadata/pkgcheck.conf` in a repo.

However, parsing and using that file could work in some fashion for repos but that would require support beyond what https://github.com/pkgcore/pkgcheck/pull/216 does currently.

**Comment by radhermit** [comment]
An initial bundled config now defines a GentooCI checkset that matches error level results for Gentoo's CI setup: https://github.com/pkgcore/pkgcheck/commit/f94d224aeb06b1fe5d5e4e031bac7cf4c43bef3b. For example, to use it for exit failures: `pkgcheck scan --exit GentooCI`.

**Comment by ezzieyguywuf** [comment]
This is great news thanks!

Please excuse my formatting i don't know how to make my gmail mobile client
switch to plaintext...
