### ISSUE TITLE
pkgcheck scan =foo/bar-X.Y.Z reports NonsolvableDeps* for other versions

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#293]
In previous pkgcheck versions, specifying an exact version of a package caused pkgcheck to test only that version. However, in the recent versions pkgcheck seems to check all versions nevertheless, e.g.:

```
$ pkgcheck scan =llvm-10.0.1
sys-devel/llvm
  PythonCompatUpdate: version 9.0.1: PYTHON_COMPAT updates available: python3_8, python3_9
  NonexistentDeps: version 11.1.0: DEPEND: nonexistent package: broom/broom
  NonexistentDeps: version 11.1.0: RDEPEND: nonexistent package: broom/broom
  NonsolvableDepsInDev: version 11.1.0: nonsolvable depset(depend) keyword(~amd64) dev profile (default/linux/amd64/17.0/x32) (38 total): solutions: [ broom/broom ]
  NonsolvableDepsInDev: version 11.1.0: nonsolvable depset(rdepend) keyword(~amd64) dev profile (default/linux/amd64/17.0/x32) (38 total): solutions: [ broom/broom ]
  NonsolvableDepsInStable: version 11.1.0: nonsolvable depset(depend) keyword(~amd64) stable profile (default/linux/amd64/17.1) (49 total): solutions: [ broom/broom ]
  NonsolvableDepsInStable: version 11.1.0: nonsolvable depset(rdepend) keyword(~amd64) stable profile (default/linux/amd64/17.1) (49 total): solutions: [ broom/broom ]
```

**Comment by radhermit** [comment]
This was caused by reworking pipeline to create runners per restriction.

You probably already know this, but note that when scanning directly against version restrictions, many version-related results will be skipped since they're run by checks that require package-scoped sources. In theory, the code could probably be changed to run package-level checks and filter the outputted results, but that's currently not done.

**Comment by mgorny** [comment]
Yes, that's fine. After all, I'm running only one specific check.
