### ISSUE TITLE
PythonCompatUpdate for lua and ruby, too

### ISSUE THREAD

**Issue by juippis** [pkgcore/pkgcheck#304]
This just popped to my mind and I wanted to let it out somewhere and you were not in IRC.

I didn't see duplicate for this, nor it being documented in https://pkgcore.github.io/pkgcheck/man/pkgcheck.html yet.

**Comment by arthurzam** [comment]
While I agree with the idea, and it is quite simple to add, I have asked people of lua & ruby projects if they would like that, and in multiple times they rejected it.

**Comment by juippis** [comment]
Thanks for trying!

**Comment by thesamesam** [comment]
I don't know if it makes sense for Lua because Lua often requires proper porting between versions, but for Python and Ruby, it's _largely_ a function of whether one's deps are ready + usually a small amount of porting work in the package itself, if any.

I think the check at least is well-defined for Ruby, even if we don't enable it by default. I'd find this pretty useful over having to do what we used to for Python - manually adding to PYTHON_COMPAT, then running `pkgcheck scan` to look for dep errors.
