### ISSUE TITLE
UnusedInherits on multilib and EAPI 5

### ISSUE THREAD

**Issue by atupone** [pkgcore/pkgcheck#351]
EAPI 5 does not provide get_libdir and inherit multilib is needed.

**Comment by mgorny** [comment]
Please paste the full output along with package name.

**Comment by atupone** [comment]
pkgcheck scan tclperl-3.2-r1.ebuild

dev-tcltk/tclperl
  UnusedInherits: version 3.2-r1: unused eclass: multilib
  DeprecatedEapi: version 3.2-r1: uses deprecated EAPI 5

Thank

**Comment by radhermit** [comment]
There are two ways to solve this:

1. Make the conditionalized EAPI default to 0 when unset for the multilib eclass in https://github.com/gentoo/gentoo/blob/master/eclass/multilib.eclass#L57.

2. Rewrite global eclass parsing to use tree-sitter instead of its simple sourcing mechanism in https://github.com/pkgcore/pkgcore/blob/master/src/pkgcore/ebuild/eclass.py#L352 so it can scan past conditionals looking for global funcs/vars in a more robust fashion.

I'd advise taking route #1 if you want a quick fix for this specific issue.
