### ISSUE TITLE
network checks are performed for old versions even though they are not displayed

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#391]
Since URL results are of `FilteredVersionResult` class, they are not displayed for old versions. However, pkgcheck (unnecessarily) still issues requests for all the URIs — so we're basically DoS-ing the servers to check something that we won't report.

To be honest, this whole `FilteredVersionResult` logic doesn't make much sense to me. We should really be filtering packages on input, not output (i.e. not doing checks on packages if we're not going to use the results).

@radhermit, any reason it was done like this?

**Comment by mgorny** [comment]
I'm going to try replacing with another source class.

**Comment by mgorny** [comment]
Eh, I give up. I can't figure out why this fancy thing doesn't work. I mean, even plain `-f latest` doesn't seem to work for `_NetCheck`.

**Comment by radhermit** [comment]
> Since URL results are of `FilteredVersionResult` class, they are not displayed for old versions. However, pkgcheck (unnecessarily) still issues requests for all the URIs — so we're basically DoS-ing the servers to check something that we won't report.
> 
> To be honest, this whole `FilteredVersionResult` logic doesn't make much sense to me. We should really be filtering packages on input, not output (i.e. not doing checks on packages if we're not going to use the results).
> 
> @radhermit, any reason it was done like this?

It used to not issue requests for all URIs, or at least I remember explicitly checking that when writing the network checks initially. Something probably got broken along the way when trying to work towards customizable filtering running on top of python's weak parallelization support. I'd recommend adding unit tests to verify future work doesn't alter things again.

In terms of why FilteredVersionResult exists, iirc it's because it was working towards being able to filter checks at different scope levels and allowing a check's related results to request filtering be done on them by default while also allowing the user to disable that filtering if requested. I forget the timeline of events, but I may have worked on the base of that configurable filtering support before general parallelization was added and that broke the previous filtering design that assumed it was running in serial, viewing all pkgs that were to be checked.

Your change makes it so the source is always filtered without it being configurable and only supports it at a certain scope level, meaning you'd probably have to add sources at all scope levels if you required filtering for them.
