### ISSUE TITLE
Ebuild sourcing failures are not reported

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#41]
If ebuild fails to source, pkgcheck throws an exception on the console and aborts the check, instead of adding an appropriate report and skipping the version.

Maybe we could fix it via wrapping the repository objects.

**Comment by ferringb** [comment]
+1 on the repository wrapper approach; I'd been thinking about doing
something similar to that for a while, just never got around to it.  It
would make EAPI interactions (when the EAPI is unsupported) likely more
simple, at the cost of making the consuming API a bit more of a PITA.

**Comment by radhermit** [comment]
Closing since the auto-masking of ebuilds with bad metadata, invalid bash, etc that pkgcore does now should be caught and reported by pkgcheck via the MetadataReport check.

The pkgcore side will probably be reworked in the future to give the auto-hidden pkgs more visibility when the related pkgs are directly requested by the resolver, but that shouldn't affect pkgcheck usage much other than minor API tweaks.
