### ISSUE TITLE
Detect missing remote-ids based on SRC_URI

### ISSUE THREAD

**Issue by thesamesam** [pkgcore/pkgcheck#475]
pkgcheck could detect missing remote-ids in metadata.xml by checking SRC_URI in ebuilds.

For example, if an ebuild has `SRC_URI="https://github.com/foo/bar/..."` but no remote-id in metadata.xml, we should warn about a missing element in there: `<remote-id type="github">foo/bar</remote-id>`.

**Comment by arthurzam** [comment]
Some notes for myself:

Reusing the definitions under `MetadataUrlCheck` won't be possible, as various SRC_URI have separate URL scheme than the one for remote-id (for example pypi). This means this check will need separate dict and extraction value for remote-id.

I want to minimize false positive, so some extra rules:
- Don't suggest anything for remote-id `x` if it already has `x` defined (some other value).
- Try to check if I can filter the fetchables by non-use-restricted (to minimize catch for `test?` extra tarballs)
- Decide how to work with mirrors (like `mirror://pypi`)? Maybe some extra match rules?

  On the same note, maybe a new check to catch when using straight pypi hosted files instead of shorter `mirror://pypi`?
