### ISSUE TITLE
Checks for missing inherits / private API

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#50]
I guess we could steal the crazy regexp from repoman and see how well it works.

Though instead of hardcoded function tables, I'd rather use some minimal eclass scanning with eclassdoc support. Grab all functions defined in eclass, split them into private and public based on eclassdoc, complain about the former in general and about missing inherits when the latter is used.

We should probably also add some `@TAG` for allowed implicit inherits.

**Comment by radhermit** [comment]
I think this is going to have to wait until my bash parser/ast work is usable as I'm not going to use regexps for this.

**Comment by radhermit** [comment]
This should now be possible with eclass doc parsing support albeit using some manual scanning scheme since bash parsing support isn't there yet. It might be wise to use something potentially faster than straight regexes to find usage matches since some of the regexes could be somewhat unwieldy. Some sort of hybrid, trie-based approach like the [flashtext algorithm](https://github.com/vi3k6i5/flashtext) might be worth looking into.

**Comment by radhermit** [comment]
Just to note, I got this working using plain regexes, but as expected it runs into false positive issues due to conditionals which would require actual bash parsing support or absolutely ugly workarounds.

**Comment by radhermit** [comment]
Just to note, the related check that was merged will probably never be enabled by default until bash parsing is supported, but I thought it had enough value to add as an optionally run check.
