### ISSUE TITLE
Check for eclassdoc syntax

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#74]
Could you include eclassdoc syntax checks, please? I'm particularly thinking of issues that cause eclass-manpages build to fail.

**Comment by radhermit** [comment]
Link to eclass doc formatting reference in the devmanual: https://devmanual.gentoo.org/eclass-writing

Support for parsing this should probably be added to the pkgcore side so it possible could be used for other scripts more easily.

**Comment by radhermit** [comment]
Initial implementation for eclass doc parsing, checks, and cache in the eclass branch. After playing around with all types of python parsing libs and solutions, I just found it easier to roll a manual, regex-based parser to make error reporting easier and more relevant in order to throw proper results for the related check.

**Comment by radhermit** [comment]
The parsing support might be moved to the pkgcore side later as mentioned earlier once support matures in order to support doc generation, scripting, and related tasks targeting eclasses.
